# Generated by Django 3.0.2 on 2020-01-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20200102_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.TextField(max_length=100),
        ),
    ]
