# Generated by Django 3.0.2 on 2020-01-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20200103_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['headline', 'subtitle', 'text', 'pub_date']},
        ),
    ]
