# Generated by Django 3.0.2 on 2020-01-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20200105_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
