# Generated by Django 3.0.2 on 2020-01-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_auto_20200105_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
