# Generated by Django 3.0.2 on 2020-01-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_auto_20200105_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
