# Generated by Django 3.0.2 on 2020-01-05 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0017_auto_20200105_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auto_increment_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='article_id',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
